### ISSUE TITLE
Could you include it so that  "s.to" will work also?

### ISSUE THREAD

**Issue by MacDos** [Bungeefan/BurningSeriesControls#1]
My provider/vpn won't work with BurningSeries, I have already changed the 
"full-screen-api.allow-trusted-requests-only" >>"false" but I have no success on the working "s.to" alternative website.

**Comment by Bungeefan** [comment]
The `full-screen-api.allow-trusted-requests-only` property is only for the plugin to allow toggling the full screen in the browser, it has nothing to do with the IP/DNS block from your ISP.

And for s.to, have a look at: https://addons.mozilla.org/firefox/addon/serienstream-controls/
